name: Integration

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  deploy-seal-key-server:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy the ci key server
        uses: peter-evans/repository-dispatch@ff45666b9427631e3450c54a1bcbee4d9ff4d7c0 # pin@v3.0.0
        with:
          repository: MystenLabs/sui-operations
          token: ${{ secrets.SEAL_DEPLOY_DISPATCH_TOKEN }}
          event-type: seal-deploy-ci
          client-payload: '{"seal_key_server_commit": "${{ github.sha }}", "environment": "ci"}'